apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ValeriiaFediuk/my-microservice-project.git"
    targetRevision: lesson-9
    path: charts/django-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: django
  syncPolicy:
    automated:
      prune: true
      selfHeal: true